### ISSUE TITLE
rgb_to_hex.cc bug

### ISSUE THREAD

**Issue by jeffcooperr** [83n70/Open-Source-Collab#14]
Issue/Bug Report

Line 7, integer 265 needs to be changed to 255

Steps to Reproduce
1. change 6 to 5
Currrent: `    r = std::max(0, std::min(265, r));
`
Fixed: `    r = std::max(0, std::min(255, r));
`
Expected Behavior: the color will output correctly

Actual Behavior: color is not accurate

Impact What is the impact of this issue/bug? medium

**Comment by swhitcomb23** [comment]
I fixed the bug Jeff

**Comment by swhitcomb23** [comment]
Fixed
