### ISSUE TITLE
Issue report rgb.hex.java

### ISSUE THREAD

**Issue by OwenDonohoe1** [83n70/Open-Source-Collab#15]
On the 7th line the "b" value is printed twice rather than once, and the g value is not printed.
   `System.out.println("RGB color (" + r + ", " + b + ", " + b + ") = " + hexColor);`
        - Change first "b" to "g"

**Comment by 83n70** [comment]
Corrected issue.
Changed center b to g to correct the printing to be r g b instead of r b b (duplicate blue value instead of green value)
