### ISSUE TITLE
RGB to hex java rgb values wrong

### ISSUE THREAD

**Issue by Sokenro** [83n70/Open-Source-Collab#17]
When running the program the printed values for rgb do not match the hex value.

the program should output "RGB color (255, 127, 0) = FF7F00"

the program actually outputs "RGB color (255, 0, 0) = FF7F00"

Operating System: windows 11

Possible Solution If you have any suggestions for a possible solution, please include them here.
The println should be r g b rather than r b b

Priority How critical is this issue/bug? Low, medium, or high priority?
low priority issue only effects the print to the terminal, the program still converts the rgb value given to the correct hex.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
the bug always happens when the program is run.

Impact What is the impact of this issue/bug? Low, medium, or high?
medium impact any user will spot the problem quickly.

**Comment by 83n70** [comment]
Issue has been fixed in prior issue. Issue report rgb.hex.java.
