### ISSUE TITLE
Bug report for remove_duplicates.cc

### ISSUE THREAD

**Issue by edwardgimlinschool** [83n70/Open-Source-Collab#19]
Description: The program does not alter the original array

Expected Behavior: Removed all duplicate numbers in an array and return the original array, the unique numbers in the array and the removed numbers

Actual Behavior: all the arrays are the same

Additional Information

Operating System: macOS
Browser: Safari

Possible Solution: i>n in the for-loop on line 13 should be changed to i<n, because i starts at 0.

No related issues that I know of

Priority: high

Reproducibility: it happens with every run

Impact: high

**Comment by nmckew** [comment]
Fixed the issue
